export const R = 6371000;
const rad = Math.PI / 180;
export function distance(a,b){const la=a[1]*rad,lb=b[1]*rad;return 2*R*Math.asin(Math.sqrt(Math.min(1,Math.sin((lb-la)/2)**2+Math.cos(la)*Math.cos(lb)*Math.sin((b[0]-a[0])*rad/2)**2)));}
export function routeLength(segments){return segments.reduce((s,ps)=>s+ps.slice(1).reduce((v,p,i)=>v+distance(ps[i],p),0),0);}
export function boundsOf(segments){let west=180,east=-180,south=90,north=-90;for(const ps of segments)for(const p of ps){west=Math.min(west,p[0]);east=Math.max(east,p[0]);south=Math.min(south,p[1]);north=Math.max(north,p[1]);}return {west,east,south,north};}
export function bufferedBounds(segments,buffer=1000){const b=boundsOf(segments),lat=(b.north+b.south)/2,dlat=buffer/111195,dlon=dlat/Math.max(.02,Math.cos(lat*rad));return {west:Math.max(-180,b.west-dlon),east:Math.min(180,b.east+dlon),south:Math.max(-85,b.south-dlat),north:Math.min(85,b.north+dlat)};}
export function areaKm2(b){return distance([b.west,b.south],[b.east,b.south])*distance([b.west,b.south],[b.west,b.north])/1e6;}
export function mapQuery(b){const area=areaKm2(b);if(!Object.values(b).every(Number.isFinite)||b.east<=b.west||b.north<=b.south||area>102)throw Error('地圖分區過大或無效。');const box=[b.south,b.west,b.north,b.east].map(n=>n.toFixed(6)).join(',');return `[out:json][timeout:60][maxsize:33554432];(way[highway](${box});way[waterway](${box});way[natural](${box});relation[natural](${box});way[landuse](${box});relation[landuse](${box});way[leisure](${box});relation[leisure](${box});way[boundary=protected_area](${box});relation[boundary=protected_area](${box});way[building](${box});relation[building](${box});nwr[amenity](${box});nwr[tourism](${box});nwr[shop](${box});nwr[place](${box});nwr[historic](${box});nwr[information](${box});node[natural~"^(peak|saddle|spring|cave_entrance)$"](${box});node[man_made~"^(tower|water_tower|survey_point)$"](${box});node[highway~"^(trailhead|bus_stop)$"](${box}););out geom;`;}
export function validateMap(data){if(!data||!Array.isArray(data.elements)||data.elements.some(e=>!e||typeof e!=='object'))throw Error('伺服器未傳回有效地圖。');if(data.remark)throw Error('地圖服務未能完成整個範圍，請稍後重試或縮小範圍。');if(!data.elements.length)throw Error('呢個範圍未有取得道路／水道資料，未標示為下載完成。');return data;}
export function joinWays(paths){const pending=paths.map(p=>p.slice()),result=[],eq=(a,b)=>a&&b&&a[0]===b[0]&&a[1]===b[1];while(pending.length){let path=pending.shift(),changed=true;while(changed&&!eq(path[0],path.at(-1))){changed=false;for(let i=0;i<pending.length;i++){let next=pending[i];if(eq(path.at(-1),next[0]))next.slice(1).forEach(p=>path.push(p));else if(eq(path.at(-1),next.at(-1)))next.slice(0,-1).reverse().forEach(p=>path.push(p));else if(eq(path[0],next.at(-1)))path=[...next.slice(0,-1),...path];else if(eq(path[0],next[0]))path=[...next.slice(1).reverse(),...path];else continue;pending.splice(i,1);changed=true;break;}}result.push(path);}return result;}
export function nearestDistance(p,segments){const c=Math.cos(p[1]*rad);let result=Infinity;const xy=q=>[(q[0]-p[0])*rad*R*c,(q[1]-p[1])*rad*R];for(const s of segments)for(let i=1;i<s.length;i++){const a=xy(s[i-1]),b=xy(s[i]),dx=b[0]-a[0],dy=b[1]-a[1],len=dx*dx+dy*dy,t=len?Math.max(0,Math.min(1,-(a[0]*dx+a[1]*dy)/len)):0;result=Math.min(result,Math.hypot(a[0]+dx*t,a[1]+dy*t));}return result;}
export const project=p=>[R*p[0]*rad,-R*Math.log(Math.tan(Math.PI/4+Math.max(-85,Math.min(85,p[1]))*rad/2))];
export const unproject=p=>[p[0]/R/rad,(2*Math.atan(Math.exp(-p[1]/R))-Math.PI/2)/rad];
export function validCoordinate(p){return p.length>=2&&p.slice(0,2).every(Number.isFinite)&&Math.abs(p[0])<=180&&Math.abs(p[1])<=85;}
const nodes=(d,t)=>[...d.getElementsByTagNameNS('*',t)];
const childText=(d,t)=>[...d.children].find(x=>x.localName===t)?.textContent?.trim();
export function parseRoute(text,filename,Parser=globalThis.DOMParser){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('唔接受含外部宣告嘅 XML 檔案。');const d=new Parser().parseFromString(text,'application/xml');if(nodes(d,'parsererror').length||d.documentElement.localName==='parsererror')throw Error('XML 格式有錯，請重新匯出 GPX／KML。');let name=filename.replace(/\.(gpx|kml)$/i,''),segments=[],waypoints=[];const root=d.documentElement.localName;const gpxPoint=n=>{if(!n.hasAttribute('lon')||!n.hasAttribute('lat')||!n.getAttribute('lon').trim()||!n.getAttribute('lat').trim())throw Error('路線缺少座標。');const p=[Number(n.getAttribute('lon')),Number(n.getAttribute('lat'))];const e=childText(n,'ele');if(e!==undefined&&e!==''&&Number.isFinite(Number(e)))p.push(Number(e));return p;};
if(root==='gpx'){const tracks=nodes(d,'trk');name=tracks.length===1?childText(tracks[0],'name')||name:name;for(const s of [...nodes(d,'trkseg'),...nodes(d,'rte')]){const points=nodes(s,s.localName==='rte'?'rtept':'trkpt').map(gpxPoint);if(points.length>=2)segments.push(points);}waypoints=nodes(d,'wpt').map(w=>({name:childText(w,'name')||'標記',point:gpxPoint(w)}));}
else if(root==='kml'){const doc=nodes(d,'Document')[0];name=doc?childText(doc,'name')||name:name;const coords=n=>(nodes(n,'coordinates')[0]?.textContent||'').trim().split(/\s+/).filter(Boolean).map(t=>{const v=t.split(',');if(v.length<2||!v[0].trim()||!v[1].trim())throw Error('KML 座標缺少經緯度。');return v.map(Number);});for(const s of nodes(d,'LineString')){const points=coords(s);if(points.length>=2)segments.push(points);}for(const s of nodes(d,'Track')){const points=nodes(s,'coord').map(x=>x.textContent.trim().split(/\s+/).map(Number));if(points.length>=2)segments.push(points);}for(const w of nodes(d,'Placemark')){const point=nodes(w,'Point')[0];if(point&&coords(point)[0])waypoints.push({name:childText(w,'name')||'標記',point:coords(point)[0]});}}
else throw Error('請使用 GPX 或 KML 檔案；KMZ 請先解壓成 KML。');
let count=0;for(const s of segments)for(const p of s){count++;if(!validCoordinate(p))throw Error('座標無效或超出支援緯度 ±85°。');}if(!count)throw Error('檔案內冇路線軌跡；只有標記嘅檔案唔能夠計算路線。');if(count>100000)throw Error('座標超過 100,000 點，請先簡化或分段。');if(waypoints.some(w=>!validCoordinate(w.point)))throw Error('檔案標記包含無效座標。');const b=boundsOf(segments);if(b.east-b.west>180)throw Error('暫未支援跨越國際換日線嘅路線，請先分段。');return {id:crypto.randomUUID(),name:name.slice(0,160),segments,waypoints,sourceName:filename,created:Date.now(),length:routeLength(segments),count,buffer:1000};}
