import {distance,validCoordinate} from './core.mjs';
const allowed=new Set(['path','footway','track','steps','pedestrian','living_street','residential','service','unclassified','tertiary','secondary','primary','cycleway','bridleway']);
const key=p=>p[0].toFixed(6)+','+p[1].toFixed(6);
function walkable(tags={}){return allowed.has(tags.highway)&&tags.access!=='private'&&tags.access!=='no'&&tags.foot!=='no'&&tags.foot!=='use_sidepath'&&tags.construction===undefined;}
function penalty(tags={}){if(tags.highway==='steps')return 1.8;if(tags.highway==='track'||tags.highway==='bridleway')return 1.25;if(['primary','secondary'].includes(tags.highway)&&!tags.sidewalk)return 2.5;return 1;}
export function buildRoutingGraph(elements=[]){const nodes=[],lookup=new Map(),edges=[];const node=p=>{const k=key(p);if(lookup.has(k))return lookup.get(k);const id=nodes.length;nodes.push([+p[0].toFixed(6),+p[1].toFixed(6)]);lookup.set(k,id);return id;};for(const e of elements){if(e.type!=='way'||!walkable(e.tags)||!Array.isArray(e.geometry))continue;const points=e.geometry.map(p=>[p.lon,p.lat]).filter(validCoordinate),cost=penalty(e.tags);for(let i=1;i<points.length;i++){const a=node(points[i-1]),b=node(points[i]),w=Math.round(distance(points[i-1],points[i])*cost);if(a===b||!w)continue;edges.push([a,b,w],[b,a,w]);}}if(nodes.length>150000||edges.length>500000)throw Error('步道路網太大，請縮小下載範圍。');return {version:1,nodes,edges};}
export function nearestGraphNode(graph,point,maxDistance=400){if(!graph?.nodes?.length||!validCoordinate(point))return null;let id=-1,best=Infinity;for(let i=0;i<graph.nodes.length;i++){const d=distance(point,graph.nodes[i]);if(d<best){best=d;id=i;}}return best<=maxDistance?{id,distance:best}:null;}
function push(heap,item){heap.push(item);let i=heap.length-1;while(i){const p=(i-1)>>1;if(heap[p][0]<=item[0])break;heap[i]=heap[p];i=p;}heap[i]=item;}
function pop(heap){const top=heap[0],last=heap.pop();if(heap.length&&last){let i=0;while(true){let c=i*2+1;if(c>=heap.length)break;if(c+1<heap.length&&heap[c+1][0]<heap[c][0])c++;if(heap[c][0]>=last[0])break;heap[i]=heap[c];i=c;}heap[i]=last;}return top;}
export function routeAStar(graph,start,end,{maxVisited=200000,maxSnap=400}={}){const a=nearestGraphNode(graph,start,maxSnap),b=nearestGraphNode(graph,end,maxSnap);if(!a||!b)throw Error('起點或終點距離已下載步道超過 400 m。');const adj=Array.from({length:graph.nodes.length},()=>[]);for(const [u,v,w] of graph.edges)if(adj[u]&&adj[v])adj[u].push([v,w]);const n=graph.nodes.length,g=new Float64Array(n);g.fill(Infinity);g[a.id]=0;const parent=new Int32Array(n);parent.fill(-1);const open=[];push(open,[distance(graph.nodes[a.id],graph.nodes[b.id]),a.id]);const closed=new Uint8Array(n);let visited=0;while(open.length){const [,u]=pop(open);if(closed[u])continue;closed[u]=1;if(++visited>maxVisited)throw Error('路網計算量過大，請縮短路段。');if(u===b.id)break;for(const [v,w] of adj[u]){const next=g[u]+w;if(next>=g[v])continue;g[v]=next;parent[v]=u;push(open,[next+distance(graph.nodes[v],graph.nodes[b.id]),v]);}}if(!Number.isFinite(g[b.id]))throw Error('已下載步道之間沒有可通行連接。');const ids=[];for(let u=b.id;u!==-1;u=parent[u])ids.push(u);ids.reverse();const path=[start,...ids.map(i=>graph.nodes[i]),end],clean=[];for(const p of path)if(!clean.length||distance(clean.at(-1),p)>.5)clean.push(p);return {path:clean,distance:g[b.id],snaps:[a.distance,b.distance],visited};}
